name: Other
description: Use this for any other issues. PLEASE do not create blank issues
title: "[OTHER]"
labels: ["awaiting triage"]
body:
  - type: markdown
    attributes:
      value: "# Other issue"
  - type: textarea
    id: issuedescription
    attributes:
      label: What would you like to share?
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this issue?
    validations:
      required: false
  - type: checkboxes
    id: consent
    attributes:
      label: Would you like to work on this issue?
      description: Check this if you want else leave that
      options:
        - label: Yes
          required: false
  - type: checkboxes
    id: cat-preferences
    attributes:
      label: What kinds of cats do you like?
      description: You may select more than one.
      options:
        - label: Orange cat
          required: true
        - label: **Black cat**
